name: u-s2s
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - ca-certificates=2021.10.8=ha878542_0
  - cereal=1.3.1=hd8ed1ab_0
  - fasttext=0.9.2=py38h1fd1430_3
  - gettext=0.19.8.1=h73d1719_1008
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=13_linux64_openblas
  - libcblas=3.9.0=13_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libflac=1.3.3=h9c3ff4c_1
  - libgcc-ng=11.2.0=h1d223b6_12
  - libgfortran-ng=11.2.0=h69a702a_12
  - libgfortran5=11.2.0=h5c6108e_12
  - liblapack=3.9.0=13_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libopus=1.3.1=h7f98852_1
  - libsndfile=1.0.31=h9c3ff4c_1
  - libstdcxx-ng=11.2.0=he4da1e4_12
  - libvorbis=1.3.7=h9c3ff4c_0
  - libzlib=1.2.11=h36c2ea0_1013
  - llvm-openmp=13.0.1=hf817b99_0
  - mkl=2022.0.1=h8d4b97c_803
  - ncurses=6.3=h9c3ff4c_0
  - numpy=1.22.2=py38h6ae9a64_0
  - openssl=3.0.0=h7f98852_2
  - packaging=21.3=pyhd8ed1ab_0
  - pip=22.0.3=pyhd8ed1ab_0
  - pybind11=2.9.1=py38h1fd1430_0
  - pybind11-global=2.9.1=py38h1fd1430_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - python=3.8.12=hf930737_2_cpython
  - python_abi=3.8=2_cp38
  - readline=8.1=h46c0cb4_0
  - setuptools=59.5.0=py38h578d9bd_0
  - sqlite=3.37.0=h9cd32fc_0
  - tbb=2021.5.0=h4bd325d_0
  - tk=8.6.11=h27826a3_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h36c2ea0_1013
prefix: /home/b07502072/.conda/envs/u-s2s
